version: "3.7"
services:
  localexterncrm:
    image: registry.gitlab.com/localexterncrm-team1/localextercrmbackend:latest
    labels:
      com.docker.stack.namespace: "devops"
    environment:
      - RESOURCE_SERVER_STORE=/app/uploads/
      - RESOURCE_SERVER_STORE_URL=https://afb-api.skysoft.cm/uploads/
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -Dspring.profiles.active=prod
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/localexterncrm?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Afbs2021
    networks:
      - devops_web_network
    volumes:
      - ~/:/app/uploads
    deploy:
      mode: replicated
      replicas: 1

networks:
  devops_web_network:
      name: devops_web_network
